version: "3.9" # https://docs.docker.com/compose/gettingstarted/
services:
  postgres:
    image: postgres:16.1
    container_name: postgres_rnp
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalogdb
    ports:
      - "5432:5432"

  pgadmin4:
    container_name: pgadmin4_rnp # http://localhost:5050/
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.co
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "5050:80"